<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/default.php 
 * 
 * Contao extension: syncCto 2.0.0 beta2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['edit'] = "Éditer";
$GLOBALS['TL_LANG']['MSC']['copy'] = "Dupliquer";
$GLOBALS['TL_LANG']['MSC']['syncTo'] = "Synchroniser le client";
$GLOBALS['TL_LANG']['MSC']['syncFrom'] = "Synchroniser le serveur";
$GLOBALS['TL_LANG']['MSC']['restore_backup'] = "Restaurer la sauvegarde";
$GLOBALS['TL_LANG']['MSC']['start_backup'] = "Démarrer la sauvegarde";
$GLOBALS['TL_LANG']['MSC']['ok'] = "OK";
$GLOBALS['TL_LANG']['MSC']['progress'] = "En cours";
$GLOBALS['TL_LANG']['MSC']['error'] = "Erreur";
$GLOBALS['TL_LANG']['MSC']['skipped'] = "Ignoré";
$GLOBALS['TL_LANG']['MSC']['unknown_step'] = "Étape inconnue";
$GLOBALS['TL_LANG']['MSC']['step'] = "Étape";
$GLOBALS['TL_LANG']['MSC']['abort'] = "Interrompre !";
$GLOBALS['TL_LANG']['MSC']['complete'] = "Terminé !";
$GLOBALS['TL_LANG']['MSC']['debug_mode'] = "Mode de débogage";
$GLOBALS['TL_LANG']['MSC']['select_all_files'] = "Sélectionner tous les fichiers";
$GLOBALS['TL_LANG']['MSC']['sync_info'] = "Veuillez, s'il vous plaît, ne pas fermer la fenêtre actuelle durant tout le processus de synchronisation.";
$GLOBALS['TL_LANG']['MSC']['state'] = "État";
$GLOBALS['TL_LANG']['MSC']['filesize'] = "Taille du fichier";
$GLOBALS['TL_LANG']['MSC']['file'] = "Fichier";
$GLOBALS['TL_LANG']['MSC']['totalsize'] = "Taille totale des fichiers:";
$GLOBALS['TL_LANG']['MSC']['new_file'] = "Nouveau";
$GLOBALS['TL_LANG']['MSC']['modified_file'] = "Modifié";
$GLOBALS['TL_LANG']['MSC']['unknown_file'] = "Inconnu";
$GLOBALS['TL_LANG']['MSC']['deleted_file'] = "Supprimé";
$GLOBALS['TL_LANG']['MSC']['big_files'] = "Volumineux";
$GLOBALS['TL_LANG']['MSC']['skipped_files'] = "Fichier(s) ignoré(s).";
$GLOBALS['TL_LANG']['MSC']['ignored_files'] = "Ignoré";
$GLOBALS['TL_LANG']['MSC']['submit_files'] = "Envoyer des fichiers";
$GLOBALS['TL_LANG']['MSC']['delete_files'] = "Supprimer les fichiers sélectionnés";
$GLOBALS['TL_LANG']['MSC']['last_sync'] = "La dernière synchronisation a été faite à %s sur %s par l'utilisateur %s (%s).";
$GLOBALS['TL_LANG']['MSC']['abort_sync']['0'] = "Interrompre";
$GLOBALS['TL_LANG']['MSC']['abort_sync']['1'] = "En cours";
$GLOBALS['TL_LANG']['MSC']['repeat_sync']['0'] = "Répéter";
$GLOBALS['TL_LANG']['MSC']['repeat_sync']['1'] = "En cours";
$GLOBALS['TL_LANG']['MSC']['run_time'] = "Running time: %s seconds";
$GLOBALS['TL_LANG']['MSC']['memory_limit'] = "Limite de mémoire: %s";
$GLOBALS['TL_LANG']['SYC']['files'] = "Fichier de synchronisation";
$GLOBALS['TL_LANG']['SYC']['backup'] = "Catégorie de sauvegarde";
$GLOBALS['TL_LANG']['SYC']['option_small']['0'] = "Données personnelles";
$GLOBALS['TL_LANG']['SYC']['option_small']['1'] = "Just selected files and folders within tl_files are considered.";
$GLOBALS['TL_LANG']['SYC']['option_full']['0'] = "Installation de Contao";
$GLOBALS['TL_LANG']['SYC']['option_full']['1'] = "L'installation complète de Contao, y compris tl_files est considérée.";
$GLOBALS['TL_LANG']['ERR']['missing_file_selection'] = "Aucun fichier(s) est/sont sélectionné(s).";
$GLOBALS['TL_LANG']['ERR']['missing_file_information'] = "Il manque soit un fichier soit une information dans un fichier.";
$GLOBALS['TL_LANG']['ERR']['unknown_file'] = "Le fichier %s n'a pas pu être trouvé.";
$GLOBALS['TL_LANG']['ERR']['unknown_file_in_zip'] = "Le fichier %s n'a pas pu être trouvé dans le zip.";
$GLOBALS['TL_LANG']['ERR']['unknown_path'] = "Chemin d'accès inconnu.";
$GLOBALS['TL_LANG']['ERR']['cant_open'] = "Le fichier %s ne peut pas être ouvert.";
$GLOBALS['TL_LANG']['ERR']['checksum_error'] = "Erreur checksum.";
$GLOBALS['TL_LANG']['ERR']['cant_move_file'] = "Impossible de déplacer le fichier à partir de %s vers %s.";
$GLOBALS['TL_LANG']['ERR']['cant_delete_file'] = "Erreur de suppression du fichier.";
$GLOBALS['TL_LANG']['ERR']['missing_tables_selection'] = "Aucune table(s) est/sont sélectionné(s).";
$GLOBALS['TL_LANG']['ERR']['unknown_backup_method'] = "La méthode de sauvegarde choisie est inconnue.";
$GLOBALS['TL_LANG']['ERR']['unknown_function'] = "Fonction ou méthode inconnue.";
$GLOBALS['TL_LANG']['ERR']['64Bit_error'] = "Number overflow. Veuillez, s'il vous plaît, essayer une version 64bit de PHP.";
$GLOBALS['TL_LANG']['ERR']['maximum_filesize'] = "fichier(s) trop volumineux:";
$GLOBALS['TL_LANG']['ERR']['call_directly'] = "N'essayez pas d'exécuter la synchronisation directement.";
$GLOBALS['TL_LANG']['ERR']['client_set'] = "La communication entre le serveur et le client a échoué.";
$GLOBALS['TL_LANG']['ERR']['unknown_client'] = "Client inconnu.";
$GLOBALS['TL_LANG']['ERR']['referer'] = "The clients referrer-check could not be deactivated.";
$GLOBALS['TL_LANG']['ERR']['version'] = "Conflit de version dans %s. <br />Serveur: %s <br />Client: %s";
$GLOBALS['TL_LANG']['ERR']['upload_ini'] = "Upload sans succès. La fonction est désactivée dans le fichier php.ini";
$GLOBALS['TL_LANG']['ERR']['rebuild'] = "Error rebuilding the file(s). Chemin d'accès: %s";
$GLOBALS['TL_LANG']['ERR']['send'] = "Erreur d'envoi du(des) fichier(s).";
 
?>
