<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/explain.php 
 * 
 * Contao extension: syncCto 2.0.0 alpha2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['apiKey']['0']['0'] = "ctoCommunication clé API";
$GLOBALS['TL_LANG']['XPL']['apiKey']['0']['1'] = "La clé API permet l'encodage d'une synchronisation entre deux installations de Contao.<br /><br />The key is always generated while using the common settings. You have to copy and insert it in the specific field on the server.";
$GLOBALS['TL_LANG']['XPL']['security']['0']['1'] = "synCto offre par défaut trois types de synchronisation. Deux avec encodage et un sans encodage.<br /><br />Utiliser uniquement la synchronisation qui n'est pas encodée pour les projets internes. Sinon les attaques provenant de l'extérieur sont possibles.";
 
?>
