<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/modules.php 
 * 
 * Contao extension: syncCto 2.0.0 alpha2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['syncCto'] = "Synchronisation";
$GLOBALS['TL_LANG']['MOD']['synccto_clients']['0'] = "Clients";
$GLOBALS['TL_LANG']['MOD']['synccto_clients']['1'] = "Gérer les clients.";
$GLOBALS['TL_LANG']['MOD']['syncCto_settings']['0'] = "Paramètres";
$GLOBALS['TL_LANG']['MOD']['syncCto_settings']['1'] = "Vérifier et optimiser la configuration syncCto.";
$GLOBALS['TL_LANG']['MOD']['syncCto_backups']['0'] = "Sauvegardes";
$GLOBALS['TL_LANG']['MOD']['syncCto_backups']['1'] = "Créer et importer des sauvegardes.";
$GLOBALS['TL_LANG']['MOD']['syncCto_check']['0'] = "Vérification du système";
$GLOBALS['TL_LANG']['MOD']['syncCto_check']['1'] = "Vérifier les exigences au moyen de l'outil de diagnostic système de syncCto.";
 
?>
