<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/tl_syncCto_clients_syncTo.php 
 * 
 * Contao extension: syncCto 2.0.0 beta2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['sync_legend'] = "Paramètres de synchronisation";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['filelist_legend'] = "Fichiers et dossiers";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['table_recommend_legend'] = "Tables recommandées";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['table_none_recommend_legend'] = "Tables non recommandées";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['edit'] = "Synchronisation du client";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['sync_type']['0'] = "Type de synchronisation";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['sync_type']['1'] = "Ici vous pouvez sélectionner le type de synchronisation.";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['database_tables_recommended']['0'] = "Tables recommandées";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['database_tables_recommended']['1'] = "Ici vous pouvez sélectionner les tables recommandées pour la synchronisation.";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['database_tables_none_recommended']['0'] = "Tables non recommandées";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['database_tables_none_recommended']['1'] = "Ici vous pouvez sélectionner les tables non recommandées pour la synchronisation. A utiliser avec prudence.";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['filelist']['0'] = "Fichiers sources";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['filelist']['1'] = "Veuillez, s'il vous plaît, sélectionner un fichier ou un dossier à partir de l'explorateur de fichiers.";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['purgeData']['0'] = "Purger les données";
$GLOBALS['TL_LANG']['tl_syncCto_clients_syncTo']['purgeData']['1'] = "Veuillez, s'il vous plaît, sélectionner cette option, si vous voulez purger les données temporaires du client.";
 
?>
