<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/tl_syncCto_backup.php 
 * 
 * Contao extension: syncCto 2.0.0 beta2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_syncCto_backup']['welcome'] = "Gérer les sauvegardes";
$GLOBALS['TL_LANG']['tl_syncCto_backup']['title_backup'] = "Créer les sauvegardes";
$GLOBALS['TL_LANG']['tl_syncCto_backup']['title_restore'] = "Importer les sauvegardes";
$GLOBALS['TL_LANG']['tl_syncCto_backup']['db_backup']['0'] = "Créer une sauvegarde de la base de données";
$GLOBALS['TL_LANG']['tl_syncCto_backup']['db_backup']['1'] = "Ici vous pouvez créer une sauvegarde de la base de données.";
$GLOBALS['TL_LANG']['tl_syncCto_backup']['file_backup']['0'] = "Créer une sauvegarde des fichiers";
$GLOBALS['TL_LANG']['tl_syncCto_backup']['file_backup']['1'] = "Ici vous pouvez créer une sauvegarde des fichiers.";
$GLOBALS['TL_LANG']['tl_syncCto_backup']['db_restore']['0'] = "Importer la sauvegarde de la base de données";
$GLOBALS['TL_LANG']['tl_syncCto_backup']['db_restore']['1'] = "Ici vous pouvez importer une sauvegarde de la base de données.";
$GLOBALS['TL_LANG']['tl_syncCto_backup']['file_restore']['0'] = "Importer un fichier de sauvegarde";
$GLOBALS['TL_LANG']['tl_syncCto_backup']['file_restore']['1'] = "Ici vous pouvez importer une sauvegarde des fichiers.";
 
?>
