<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/tl_synccto_clients.php 
 * 
 * Contao extension: syncCto 2.0.0 alpha2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_synccto_clients']['new']['0'] = "Nouveau client";
$GLOBALS['TL_LANG']['tl_synccto_clients']['new']['1'] = "Nouveau client";
$GLOBALS['TL_LANG']['tl_synccto_clients']['title_legend'] = "Description du client";
$GLOBALS['TL_LANG']['tl_synccto_clients']['connection_legend'] = "Paramètres de connexion";
$GLOBALS['TL_LANG']['tl_synccto_clients']['apikey_legend'] = "Chiffrement";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['all']['0'] = "Édition multiple";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['edit']['0'] = "Éditer le client";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['edit']['1'] = "Éditer le client ID %s";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['copy']['0'] = "Dupliquer le client";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['copy']['1'] = "Dupliquer le client ID %s";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['delete']['0'] = "Supprimer le client";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['delete']['1'] = "Supprimer le client ID %s";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['show']['0'] = "Détails du client";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['show']['1'] = "Voir les détails du client ID %s";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['syncTo']['0'] = "Synchroniser le client";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['syncTo']['1'] = "Synchroniser le client ID %s";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['syncFrom']['0'] = "Synchroniser le serveur";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['syncFrom']['1'] = "Synchroniser le serveur";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['syncFromConfirm'] = "Voulez-vous vraiment synchroniser le serveur ? Les données seront chargées par le client.";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['title']['1'] = "Veuillez, s'il vous plaît, entrer le titre du client.";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['id']['0'] = "ID";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['id']['1'] = "Client ID.";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['description']['1'] = "Ici vous pouvez entrer une courte description du client.";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['address']['0'] = "Domaine";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['address']['1'] = "Veuillez, s'il vous plaît, entrer l'adresse complète de l'installation de Contao.";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['path']['0'] = "Chemin d'accès du serveur";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['path']['1'] = "Veuillez, s'il vous plaît, entrer le chemin d'accès vers l'installation si elle est située dans un sous-dossier.";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['port']['0'] = "Numéro de port";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['port']['1'] = "Veuillez, s'il vous plaît, entrer le numéro du port HTTP. La valeur par défaut est 80.";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['apikey']['0'] = "ctoCommunication clé API";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['apikey']['1'] = "Cette clé assure la communication entre les installations de Contao.";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['codifyengine']['0'] = "Chiffrement";
$GLOBALS['TL_LANG']['tl_syncCto_clients']['codifyengine']['1'] = "Veuillez, s'il vous plaît, choisir l'algorithme de chiffrement.";
 
?>
