<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/tl_syncCto_steps.php 
 * 
 * Contao extension: syncCto 2.0.0 beta2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_1']['description_1'] = "Vérification du client.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_1']['description_2'] = "Purger le dossier temp.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_2']['description_1'] = "Vérification et transfert de la liste MD5.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_2']['description_2'] = "Rechercher des fichiers supprimables.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_2']['description_3'] = "Loading compare list.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_2']['description_4'] = "%s new, %s modified, %s deleted and %s not deliverable file(s) are found.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_3']['description_1'] = "Traitement des fichiers volumineux.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_3']['description_2'] = "%s of %s large file(s) have been processed.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_3']['description_3'] = "Assembler les fichiers volumineux";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_3']['description_4'] = "%s of %s large file(s) have been transferred.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_4']['description_1'] = "Création des scripts SQL";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_4']['description_2'] = "Transfert des scripts SQL";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_4']['description_3'] = "Importation des scripts SQL";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_4']['description_4'] = "Le fichier SQL a été transféré et importé avec succès.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_5']['description_1'] = "Traitement des fichiers.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_5']['description_2'] = "%s of %s files were transferred.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_5']['description_3'] = "Importer les fichiers de configuration.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_5']['description_4'] = "Fichier(s) sera/seront ignoré(s).";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_5']['description_5'] = "Fichier(s) envoyé(s).";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_5']['description_6'] = "fichier(s) en attente.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_5']['description_7'] = "Fichiers transférés:";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_5']['description_8'] = "Fichiers supprimés:";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['step_5']['description_9'] = "Fichiers incorrects:";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['abort'] = "Interrompre la synchronisation et nettoyage du client.";
$GLOBALS['TL_LANG']['tl_syncCto_sync']['complete'] = "La synchronisation a été exécutée avec succès.";
 
?>
