<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/tl_syncCto_restore_file.php 
 * 
 * Contao extension: syncCto 2.0.0 beta2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_syncCto_restore_file']['filelist_legend'] = "Fichiers";
$GLOBALS['TL_LANG']['tl_syncCto_restore_file']['edit'] = "Importer une sauvegarde des fichiers";
$GLOBALS['TL_LANG']['tl_syncCto_restore_file']['filelist']['0'] = "Fichier source";
$GLOBALS['TL_LANG']['tl_syncCto_restore_file']['filelist']['1'] = "Veuillez, s'il vous plaît, sélectionner un fichier à partir de l'explorateur de fichiers.";
$GLOBALS['TL_LANG']['tl_syncCto_restore_file']['step1'] = "Extraire le fichier zip.";
$GLOBALS['TL_LANG']['tl_syncCto_restore_file']['complete'] = "Backup %s was successfully imported at %s %s.";
 
?>
