<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/tl_syncCto_check.php 
 * 
 * Contao extension: syncCto 2.0.0 alpha2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_syncCto_check']['check'] = "Vérification du système";
$GLOBALS['TL_LANG']['tl_syncCto_check']['configuration'] = "PHP configuration";
$GLOBALS['TL_LANG']['tl_syncCto_check']['parameter'] = "Paramètre";
$GLOBALS['TL_LANG']['tl_syncCto_check']['value'] = "Valeur";
$GLOBALS['TL_LANG']['tl_syncCto_check']['description'] = "Description";
$GLOBALS['TL_LANG']['tl_syncCto_check']['on'] = "On";
$GLOBALS['TL_LANG']['tl_syncCto_check']['off'] = "Off";
$GLOBALS['TL_LANG']['tl_syncCto_check']['safemode']['0'] = "Safe mode";
$GLOBALS['TL_LANG']['tl_syncCto_check']['safemode']['1'] = "Le réglage recommandé est Off.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['met']['0'] = "Maximum execution time";
$GLOBALS['TL_LANG']['tl_syncCto_check']['met']['1'] = "Le réglage recommandé est de 30 ou plus.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['memory_limit']['0'] = "Memory limit";
$GLOBALS['TL_LANG']['tl_syncCto_check']['memory_limit']['1'] = "Le réglage recommandé est de 128,0 MB ou plus.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['register_globals']['0'] = "Register globals";
$GLOBALS['TL_LANG']['tl_syncCto_check']['register_globals']['1'] = "Le réglage recommandé est Off.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['file_uploads']['0'] = "File uploads";
$GLOBALS['TL_LANG']['tl_syncCto_check']['file_uploads']['1'] = "Le réglage recommandé est On.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['umf']['0'] = "Upload maximum filesize";
$GLOBALS['TL_LANG']['tl_syncCto_check']['umf']['1'] = "Le réglage recommandé est de 8,0 MB ou plus.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['pms']['0'] = "Post maximum size";
$GLOBALS['TL_LANG']['tl_syncCto_check']['pms']['1'] = "Le réglage recommandé est de 8,0 MB ou plus.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['mit']['0'] = "Maximum input time";
$GLOBALS['TL_LANG']['tl_syncCto_check']['mit']['1'] = "Le réglage recommandé est -1, 60 ou plus.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['dst']['0'] = "Default socket timeout";
$GLOBALS['TL_LANG']['tl_syncCto_check']['dst']['1'] = "Le réglage recommandé est de 30 ou plus.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['fsocket']['0'] = "Fsockopen";
$GLOBALS['TL_LANG']['tl_syncCto_check']['fsocket']['1'] = "Le réglage recommandé est On.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['fopen']['0'] = "Fopen";
$GLOBALS['TL_LANG']['tl_syncCto_check']['fopen']['1'] = "Le réglage recommandé est On.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['zip_archive']['0'] = "ZipArchive";
$GLOBALS['TL_LANG']['tl_syncCto_check']['zip_archive']['1'] = "Le réglage recommandé est On.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['suhosin']['0'] = "Suhosin";
$GLOBALS['TL_LANG']['tl_syncCto_check']['suhosin']['1'] = "Le réglage recommandé est Off.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['other_sync_issues'] = "Autres problèmes connus";
$GLOBALS['TL_LANG']['tl_syncCto_check']['explanation_sync_issues'] = "Some server configuration settings are preventing the synchronization, which cannot be detected by the system check.";
$GLOBALS['TL_LANG']['tl_syncCto_check']['known_issues'] = "Some known settings are:";
$GLOBALS['TL_LANG']['tl_syncCto_check']['suhosin_issue'] = "Suhosin is preventing the synchronization";
$GLOBALS['TL_LANG']['tl_syncCto_check']['mrl_issue'] = "The MaxRequestLen is too low";
$GLOBALS['TL_LANG']['tl_syncCto_check']['safemodehack'] = "syncCto ne peut pas être utilisé en raison de permissions d'écriture manquantes.";
 
?>
