<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/tl_syncCto_backup_db.php 
 * 
 * Contao extension: syncCto 2.0.0 alpha2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_syncCto_backup_db']['table_recommend_legend'] = "Tables recommandées";
$GLOBALS['TL_LANG']['tl_syncCto_backup_db']['table_none_recommend_legend'] = "Tables non recommandées";
$GLOBALS['TL_LANG']['tl_syncCto_backup_db']['edit'] = "Créez une sauvegarde de la base de données";
$GLOBALS['TL_LANG']['tl_syncCto_backup_db']['database_tables_recommended']['0'] = "Tables recommandées";
$GLOBALS['TL_LANG']['tl_syncCto_backup_db']['database_tables_recommended']['1'] = "Ici vous pouvez sélectionner les tables recommandées pour la sauvegarde.";
$GLOBALS['TL_LANG']['tl_syncCto_backup_db']['database_tables_none_recommended']['0'] = "Tables non recommandées";
$GLOBALS['TL_LANG']['tl_syncCto_backup_db']['database_tables_none_recommended']['1'] = "Ici vous pouvez sélectionner les tables non recommandées pour la sauvegarde. A utiliser avec prudence.";
$GLOBALS['TL_LANG']['tl_syncCto_backup_db']['step1'] = "Create SQL scripts and syncCto inserts.";
$GLOBALS['TL_LANG']['tl_syncCto_backup_db']['complete'] = "Créer une sauvegarde de la base de données sous";
$GLOBALS['TL_LANG']['tl_syncCto_backup_db']['download_backup'] = "Télécharger la sauvegarde de la base de données.";
 
?>
