<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/tl_syncCto_settings.php 
 * 
 * Contao extension: syncCto 2.0.0 beta2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_syncCto_settings']['edit'] = "Éditer la configuration de syncCto";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['blacklist_legend'] = "Liste noire des fichiers et dossiers";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['local_blacklist_legend'] = "Liste noire pour le fichier localconfig.php";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['whitelist_legend'] = "Liste blanche pour les dossiers à la racine";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['hidden_tables_legend'] = "Tables cachées";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['tables_legend'] = "Tables non recommandées";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['security_legend'] = "Chiffrement";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['debug_legend'] = "Mode de débogage";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['custom_legend'] = "Paramètres avancés";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['folder_blacklist']['0'] = "Liste noire des dossiers";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['folder_blacklist']['1'] = "Ici vous pouvez définir les dossiers qui doivent être ignorés pour la synchronisation.";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['file_blacklist']['0'] = "Liste noire des fichiers";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['file_blacklist']['1'] = "Ici vous pouvez définir les fichiers qui doivent être ignorés pour la synchronisation.";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['folder_whitelist']['0'] = "Liste blanche pour les dossiers à la racine";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['folder_whitelist']['1'] = "Ici vous pouvez définir quels dossiers à la racine doivent être considérés pour la synchronisation.";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['local_blacklist']['0'] = "localconfig.php";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['local_blacklist']['1'] = "Ici vous pouvez définir quelles données du fichier localconfig.php ne doivent pas être synchronisées.";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['database_tables']['0'] = "Tables non recommandées";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['database_tables']['1'] = "Ici vous pouvez définir les tables de la base de données que vous ne recommandez pas pour la synchronisation.";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['hidden_tables']['0'] = "Tables cachées";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['hidden_tables']['1'] = "Ici vous pouvez accorder l'accès à une ou plusieurs tables de la base de données pour la synchronisation.";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['debug_mode']['0'] = "Activer le mode de débogage";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['debug_mode']['1'] = "Affiche à l'écran des informations telles que les données synchronisées ou les données d'exécution.";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['custom_settings']['0'] = "Activer les paramètres avancés";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['custom_settings']['1'] = "Cliquez ici si vous savez ce que vous faites.";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['wait_timeout']['0'] = "Configurer \"wait_timeout\"";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['wait_timeout']['1'] = "Plus d'informations: http://goo.gl/rC5Y4";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['interactive_timeout']['0'] = "Configurer \"interactive_timeout\"";
$GLOBALS['TL_LANG']['tl_syncCto_settings']['interactive_timeout']['1'] = "Plus d'informations: http://goo.gl/VHxRK";
 
?>
