<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/tl_syncCto_backup_file.php 
 * 
 * Contao extension: syncCto 2.0.0 alpha2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['backup_legend'] = "Paramètres de sauvegarde";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['filelist_legend'] = "Fichiers et dossiers";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['edit'] = "Créer une sauvegarde des fichiers";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['backup_type']['0'] = "Type de sauvegarde";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['backup_type']['1'] = "Ici vous pouvez sélectionner le type de sauvegarde.";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['backup_name']['0'] = "Nom du fichier";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['backup_name']['1'] = "Ici vous pouvez entrer un nom facultatif pour l'identification.";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['filelist']['0'] = "Fichiers sources";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['filelist']['1'] = "Veuillez, s'il vous plaît, sélectionner un fichier ou un dossier à partir de l'explorateur de fichiers.";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['option_full'] = "Contao installation";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['option_small'] = "Données personnelles";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['step1'] = "Save contao installation/tl_files.";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['complete'] = "Créer une sauvegarde de fichiers sous";
$GLOBALS['TL_LANG']['tl_syncCto_backup_file']['download_backup'] = "Télécharger le fichier de sauvegarde.";
 
?>
