<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/tl_user.php 
 * 
 * Contao extension: syncCto 2.0.0 alpha2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['syncCto_clients']['0'] = "Clients admis";
$GLOBALS['TL_LANG']['tl_user']['syncCto_clients']['1'] = "Ici vous pouvez accorder l'accès à un ou plusieurs clients.";
$GLOBALS['TL_LANG']['tl_user']['syncCto_clients_p']['0'] = "Permissions du client";
$GLOBALS['TL_LANG']['tl_user']['syncCto_clients_p']['1'] = "Ici vous pouvez définir les permissions du client.";
$GLOBALS['TL_LANG']['tl_user']['syncCto_tables']['0'] = "Tables admises";
$GLOBALS['TL_LANG']['tl_user']['syncCto_tables']['1'] = "Ici vous pouvez accorder l'accès aux tables de la base de données.";
$GLOBALS['TL_LANG']['tl_user']['syncCto_legend'] = "Permissions du client";
$GLOBALS['TL_LANG']['tl_user']['syncCto_tables_legend'] = "Tables admises";
 
?>
