<?php
/**
 * TL_ROOT/system/modules/syncCto/languages/fr/tl_user_group.php 
 * 
 * Contao extension: syncCto 2.0.0 beta2 
 * French translation file 
 * 
 * Copyright : &copy; 2011 MEN AT WORK 
 * License   : GNU/GPL 2 
 * Author    : Andreas Isaak (menatwork-lage), http://www.men-at-work.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user_group']['syncCto_legend'] = "Permissions du client";
$GLOBALS['TL_LANG']['tl_user_group']['syncCto_tables_legend'] = "Tables admises";
 
?>
