# Example .check-author.yml

# Map multiple authors to a single one (aliasing of contributors).
mapping:
    "Stefan Heimes <stefan_heimes@hotmail.com>":
        - "stefanheimes <stefan_heimes@hotmail.com>"
        - "steanheimes <stefan_heimes@hotmail.com>"
        - "unknown <stefan@.(none)>"
    "Michael Bischof <mb@hinderlingvolkart.com>":
        - "Michael Bischof <mb@byteworks.ch>"
    "MEN AT WORK Bot <vcs@men-at-work.de>":
        - "MEN AT WORK <cms@men-at-work.de>"
        - "MEN AT WORK Bot <cms@men-at-work.de>"

ignore:
    - MEN AT WORK Bot <vcs@men-at-work.de>

copy-left:
    "Stefan Heimes <stefan_heimes@hotmail.com>":
        - "AutoUpdater/Contao/Updater/AutoUpdater.php"
        - "Config/Enum.php"
        - "Data/ContentData.php"
        - "Data/GeneralDataSyncCto.php"
        - "Contao/Automator/Automator.php"
        - "Contao/Communicator/Client.php"
        - "Contao/Communicator/RemoteProcedureCall.php"
        - "Contao/Config/TableSettings.php"
        - "Contao/Controller/Ajax.php"
        - "Contao/Controller/Client.php"
        - "Contao/Controller/Backup.php"
        - "Contao/Controller/ModalDatabase.php"
        - "Contao/Controller/ModalFinder.php"
        - "Contao/Controller/Status.php"
        - "Contao/Controller/SystemCheck.php"
        - "Contao/Controller/Updater.php"
        - "Contao/Database/Operation.php"
        - "Contao/Database/Updater.php"
        - "Contao/DataProvider/Table.php"
        - "Contao/DataProvider/Table/SyncctoClients.php"
        - "Contao/ExtensionRepository/RunOnce.php"
        - "Contao/Finder/Finder.php"
        - "Contao/Sync/StepPool.php"
        - "Contao/Updater/Runonce.php"
        - "Filter/FilterIteratorBase.php"
        - "Filter/FilterIteratorFiles.php"
        - "Filter/FilterIteratorFolder.php"
        - "Helper/Helper.php"
        - "InterfaceSyncCtoStep.php"
    "Andreas Isaak <andy.jared@googlemail.com>":
        - "AutoUpdater/Contao/Updater/AutoUpdater.php"
        - "Config/Enum.php"
        - "Data/ContentData.php"
        - "Data/GeneralDataSyncCto.php"
        - "Contao/Communicator/Client.php"
        - "Contao/Communicator/RemoteProcedureCall.php"
        - "Contao/Controller/Ajax.php"
        - "Contao/Controller/Backup.php"
        - "Contao/Controller/Client.php"
        - "Contao/Controller/ModalDatabase.php"
        - "Contao/Controller/ModalFinder.php"
        - "Contao/Controller/Status.php"
        - "Contao/Controller/SystemCheck.php"
        - "Contao/Controller/Updater.php"
        - "Contao/Database/Operation.php"
        - "Contao/Database/Updater.php"
        - "Contao/DataProvider/Table.php"
        - "Contao/DataProvider/Table/SyncctoClients.php"
        - "Contao/ExtensionRepository/RunOnce.php"
        - "Contao/Finder/Finder.php"
        - "Contao/Sync/StepPool.php"
        - "Contao/Updater/Runonce.php"
        - "Filter/FilterIteratorBase.php"
        - "Filter/FilterIteratorFiles.php"
        - "Filter/FilterIteratorFolder.php"
        - "Helper/Helper.php"
        - "InterfaceSyncCtoStep.php"
    "David Maack <david.maack@arcor.de>":
        - "Contao/Controller/Client.php"
        - "Contao/Database/Operation.php"
        - "Contao/Database/Updater.php"
    "Patrick Kahl <kahl.patrick@googlemail.com>":
        - "Contao/Communicator/Client.php"
        - "Contao/Communicator/RemoteProcedureCall.php"
        - "Contao/Controller/Client.php"
        - "Contao/Controller/ModalDatabase.php"
        - "Contao/Controller/ModalFinder.php"
        - "Contao/Database/Operation.php"
        - "Contao/Database/Updater.php"
        - "Contao/DataProvider/Table.php"
        - "Contao/DataProvider/Table/SyncctoClients.php"
        - "Helper/Helper.php"
    "Tristan Lins <tristan.lins@bit3.de>":
        - "Contao/Communicator/RemoteProcedureCall.php"
        - "Contao/Controller/Ajax.php"
        - "Contao/Controller/Backup.php"
        - "Contao/Controller/Client.php"
        - "Contao/Controller/ModalFinder.php"
        - "Contao/Controller/SystemCheck.php"
        - "Contao/Database/Operation.php"
        - "Contao/Finder/Finder.php"
    "David Greminger <david.greminger@1up.io>":
        - "Contao/Controller/Client.php"
        - "Contao/Controller/ModalDatabase.php"
        - "Contao/Finder/Finder.php"
        - "Helper/Helper.php"
    "Michael Bischof <mb@hinderlingvolkart.com>":
        - "Contao/Controller/Client.php"
        - "Contao/Finder/Finder.php"
