services:
  MenAtWork\SyncCto\Services\ClientFactory:
    public: true
    arguments:
      - "@database_connection"

  MenAtWork\SyncCto\Services\SyncDataFactory:
    public: true
    arguments:
      - "@session"
