services:
  _defaults:
    autowire: true
    autoconfigure: true

  ## Contao

  MenAtWork\SyncCto\Contao\ScopeMatcher:
    public: true

  ## Controller
  MenAtWork\SyncCto\Controller\:
    resource: '../../Controller/'
    tags: [ 'controller.service_arguments' ]
